import { Produto } from "../produto";

const produtos: Produto[] = [
    {
        id: 1,
        name: "Notebook Acer Gamer Nitro 5",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 2,
        name: "Notebook Acer 3",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 4499.99,
        precoPromocional: 3895.56,
        menorPregco: 2785.89,
        maiorPreco: 5635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 3,
        name: "Notebook Azus Gamer Pro-XTZ 3",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Azus",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 4,
        name: "Notebook HP",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78, 
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
     {
        id: 5,
        name: "Notebook Acer Gamer Nitro 5",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 6,
        name: "Notebook Acer 3",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 4499.99,
        precoPromocional: 3895.56,
        menorPregco: 2785.89,
        maiorPreco: 5635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 7,
        name: "Notebook Azus Gamer Pro-XTZ 3",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Azus",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 8,
        name: "Notebook HP",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78, 
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
     {
        id: 9,
        name: "Notebook Acer Gamer Nitro 5",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 10,
        name: "Notebook Acer 3",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 4499.99,
        precoPromocional: 3895.56,
        menorPregco: 2785.89,
        maiorPreco: 5635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 11,
        name: "Notebook Azus Gamer Pro-XTZ 3",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Azus",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78,
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },
    {
        id: 12,
        name: "Notebook HP",
        descricao: "O melhor da categoria, e mais vendido do mercado",
        marca: "Acer",
        modelo: "AN515-54-58CL",
        imagem: "https://png.pngtree.com/png-clipart/20240917/original/pngtree-background-acer-laptop-png-image_16027906.png",
        nota: 4.5,
        videoReview: "",
        tags: ["Baixou"],
        precoBase: 6499.99,
        precoPromocional: 5895.56,
        menorPregco: 4785.89,
        maiorPreco: 8635.78,
        precoMedio: 6523.78, 
        especificacoes: {
            destaques: "NVIDIA GeForce RTX 2060",
            Processador: "Intel Core i7-9456H",
            Memoria: "16RAM DDR4",
            Armazenamento: "512 SSD",
            Tela: "19.7 Polegadas Full HD",
            peso: "2.5 Kg",
        }

    },

]


export default produtos